export const ADD_ITEM = 'ADD_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const TOGGLE_STATUS = 'TOGGLE_STATUS';
export const REQUEST_TASKS_SUCCESS = 'REQUEST_TASKS_SUCESS';
export const REQUEST_TASKS_FAILED = 'REQUEST_TASKS_FAILED';